In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Creating array

# Creating a NumPy ndarray Object
## NumPy is used to work work arrays. 
## The array object in NumPy is called ndarray.
## We can create a NumPy ndarray object by using the array() function



In [12]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
print(np.__version__)

1.19.2


# Dimensions in Arrays

# Creating 0 Dimension
 

In [3]:
import numpy as np

arr = np.array(42)

print(arr)

42


# 1-D Arrays

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Array

In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
type(arr)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

# 3-D Array

In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Checking No.of Dimensions

In [20]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# NumPy Array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2],arr[3])

3 4


# Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [2]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('2nd element on 1st row: ', arr[0, 1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2


In [4]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


# Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the elemen

In [11]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 1, 1])

11


# Negative Indexing
 Use negative indexing to access an array from the end.

In [33]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# NumPy Array Slicing

# Slicing arrays
### Slicing in python means taking elements from one given index to another given index.

### We pass slice instead of index like this: [start:end].

### We can also define the step, like this: [start:end:step].
### If we don't pass start its considered 0

### If we don't pass end its considered length of array in that dimension

### If we don't pass step its considered 1

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:3])

[2 3]


# Negative Slicing

In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-2])

[5]


# STEP
- Use the step value to determine the step of the slicing

In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:6:2])

[2 4 6]


### Return every element of list in step wise

In [56]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:5:2])

[1 3 5]


# Slicing 2-D Arrays

In [57]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])

[2 3 4]


In [24]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1,0:2])

[6 7]


In [60]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2,3])

[4 9]


In [28]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# NumPy Array Shape
## shape of an array

- NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [34]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


# Reshaping arrays

## Reshape From 1-D to 2-D

In [63]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape From 1-D to 3-D

In [69]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3,4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Adding Two Matrices

In [2]:
# add matrices
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
B = array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


# Matrix Multiplication

In [3]:
# element-wise multiply matrices
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)
B = array([[1, 2, 3], [4, 5, 6]])
print(B)
C = A * B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


# Generate Random Number
- NumPy offers the random module to work with random numbers.

In [7]:
from numpy import random

x = random.randint(100)

print(x)

96


In [8]:
from numpy import random

x = random.rand()

print(x)


0.7956559135887276


In [9]:
from numpy import random

x=random.randint(100, size=(5))

print(x)


[ 5 77 35 99 59]


# Generate Random Array
-- In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.
## Integers
-- The randint() method takes a size parameter where you can specify the shape of an array.



# Generate Random Array

- Example
- Generate a 1-D array containing 5 random integers from 0 to 100:

In [15]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[99 51 57 65 91]


- Example
- Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

In [16]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)


[[41 93 34 53 69]
 [99 28 83 80 31]
 [37 97 76 11 62]]
